/**
 * Every component name this app is allowed to repeat out loud in a crash report.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY A LIST AND NOT A SHAPE — READ scrub-report.ts's "THE RULE" SECTION FIRST
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * React writes a component's name into the component stack from
 * `type.displayName || type.name`, and `type.name` is a string V8 INFERRED. It
 * infers it from whatever produced the function, and one of the things that
 * produces a function in an app like this is a data-derived key:
 *
 *     const screens = { [batch.code]: () => <Sheet /> };
 *     const Screen = screens[batch.code];   // Screen.name === 'BL240417A'
 *
 * That is the same mechanism that had `frames[].function` deleted from this
 * repo, one level up the tree, and it was MEASURED putting `BL240417A` on the
 * real Sentry wire through `extra.component_trail` before this list existed.
 * `[A-Za-z_$][A-Za-z0-9_$.]{0,63}` cannot tell that string from `Specification`
 * — nothing can, which is the whole reason the rule is a list.
 *
 * THE PROPERTY THAT MAKES THIS SAFE IS NOT THAT THE LIST IS COMPLETE. It is
 * that every string in it is an identifier that occurs in THIS REPOSITORY'S OWN
 * SOURCE. `app-component-names.guard.test.ts` asserts exactly that property,
 * name by name, against the real source tree.
 *
 * AND THAT IS NOT THE SAME AS "CANNOT BE A VALUE READ FROM A CUSTOMER PRODUCT",
 * WHICH IS WHAT THIS COMMENT USED TO CLAIM. It can be, in exactly one case: when
 * the customer's value HAPPENS TO EQUAL one of the 179 identifiers shipped
 * below. The check is string equality and it has no idea where the string it is
 * comparing came from, so a maker whose product is called `Studio` gets `Studio`
 * echoed, and the guard test cannot help — `Studio` is in our source.
 *
 * COUNTED RATHER THAN WAVED AT. Of the 166 names in `OURS`, 24 are ordinary
 * English words a product could plausibly be called:
 *
 *   Button, Canvas, Card, Check, Dialog, Divider, Field, Icon, Input, Link,
 *   Logo, Market, Pill, Row, Ruler, Section, Select, Session, Skeleton, Spec,
 *   State, Studio, Surface, Why
 *
 * and 5 more are the nouns this app's own screens are named after, which a
 * maker's range might equally use: Materials, Products, Records, Settings,
 * Billing. Twenty-nine of 166. They are enumerated rather than counted by a
 * rule, because "ordinary English word" is a judgement and a reader should be
 * able to check the judgement rather than the arithmetic.
 *
 * WHAT IT ACTUALLY COSTS is ONE WORD of a product name, in a component trail,
 * for a product whose whole name is exactly one of those twenty-nine, and only
 * when that word reached the trail as a component label. That is a small
 * residual and it is written down because the sentence it replaces said the
 * residual was zero — and in a privacy comment, overstating a protection is the
 * same class of error as understating a residual.
 *
 * NOT FIXED, AND THE REASON RATHER THAN THE SHRUG. Dropping the ordinary words
 * would cost the trail its most common labels (`Section`, `Field`, `Row`,
 * `Card`) to close a one-word leak against a product named `Row`. The trade that
 * WOULD be worth making is a shorter list containing only names that are
 * distinctively ours — and the measurement below says the trail is worth very
 * little in a production build, so that work has not been done.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW IT WAS PRODUCED, AND WHY IT IS DELIBERATELY OVER-INCLUSIVE
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * A scan of this app's own non-test `.tsx` files for
 *
 *   - `function X` / `class X` / `const X =` where X is PascalCase,
 *   - `<X` — anything rendered as a JSX element, which is how third-party
 *     components that appear in OUR tree (`Toaster`, `Route`, `NavLink`) get in,
 *   - any `displayName: 'X'`,
 *
 * with SCREAMING_CASE constants dropped. The guard test runs the same scan.
 *
 * WHY IT IS CHECKED IN RATHER THAN GENERATED BY THE BUILD. A Vite plugin
 * resolving a virtual module would remove the staleness entirely, and it was the
 * first thing tried. It does not survive contact with this repo: `vitest.config.ts`
 * is a SEPARATE config from `vite.config.ts` and carries only `react()`, so a
 * plugin added to the build would not exist under test — and the test is where
 * the safety property is asserted. The choice would be to duplicate the plugin
 * into both configs (two places to forget) or to let the suite run against a
 * list the build does not use (a test of something that does not ship). A file
 * plus a guard test is the same idea with neither problem.
 *
 * It therefore contains things that are not components at all — `Session`,
 * `HTMLDivElement`, `ParsedField` — because the regex cannot tell a generic
 * parameter from a JSX tag. THAT DIRECTION IS FREE. The risk this list carries
 * is a name in it that is NOT in our source; a name in it that is in our source
 * and is not a component is a string we shipped, which is exactly what the list
 * is for. Trimming it by hand would be work with no safety in it.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * IT WILL GO STALE, AND THAT IS THE SAME BARGAIN AS SCREEN_NAMES AND ROUTES
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Add a component and forget this file and its name is reported as `[redacted]`:
 * a trail loses a label, a customer loses nothing. The guard test deliberately
 * does NOT assert equality with the scan, because a test that reddens on every
 * new component would be a test people delete. It asserts the direction that
 * matters — nothing here that is not ours — and leaves the other one to rot
 * safely.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THE TRAIL IS WORTH IN THE BUILD THAT ACTUALLY REPORTS — MEASURED
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * THE EVIDENCE THIS PARAGRAPH USED TO CITE WAS DESTROYED BY THE THING IT WAS
 * DEFENDING, AND NOBODY RE-RAN IT. It said: "`npm run build` on this branch
 * emits no `CandleSafetySymbols`, no `PlanLadder`, no `CrashScreen`, no
 * `DerivationPanel` anywhere in `dist/assets/*.js`". Re-run today, that grep
 * finds ALL FOUR — because THIS FILE PUTS THEM THERE. The allow-list is a string
 * array in the entry chunk, so every name it protects is now shipped verbatim in
 * the bundle by the check that protects it. A grep is the wrong instrument once
 * the list exists.
 *
 * WHAT IS ACTUALLY TRUE, RE-MEASURED, on `npm run build` at this head:
 *
 *   - each of those four names occurs EXACTLY ONCE across `dist/assets/*.js`,
 *     and the one occurrence is the string literal in the array below —
 *     `grep -o '.\{60\}CrashScreen.\{60\}' dist/assets/index-*.js` prints
 *     `…"ConsentSection","CosmeticLabel","CrashScreen","CreditCardIcon"…`;
 *   - the BINDINGS are gone: `CandleSafetySymbols` does not appear in
 *     `ArtefactRenderer-*.js`, `PlanLadder` does not appear in `Billing-*.js`,
 *     `DerivationPanel` does not appear in `Specification-*.js` — which are the
 *     chunks that define them. Zero occurrences each. So the underlying claim —
 *     esbuild mangles our component names out of production — holds; the
 *     evidence for it is "not in the chunk that defines it", not "not in the
 *     bundle".
 *   - of the 166 names in `OURS`, 23 occur in the bundle somewhere OTHER than
 *     this array (word-boundary match across `dist/assets/*.js`): ArtefactDesigner,
 *     ArtefactRenderer, AuthProvider, Billing, Canvas, Check, EntitlementProvider,
 *     ErrorBoundary, Link, Market, Materials, Products, ProductsProvider, Records,
 *     Route, Section, Session, Settings, Specification, Studio, Surface, Why,
 *     WorkspaceProvider. The other 143 ship only as an entry in this list.
 *     Spot-checked rather than exhaustively classified, and every one looked at
 *     was a STRING and not a binding: a navigation label (`{label:"Studio"}`), an
 *     `aria-label` (`"Canvas"`), a piece of UI copy (`"Why"`), a chunk filename
 *     in an import (`./ArtefactRenderer-BGC0JkHv.js`), a provider-hook throw
 *     message, or a library's own property name (react-router has an
 *     `ErrorBoundary` route field). That is consistent with esbuild mangling
 *     bindings and not string literals — but it is a spot check, so read it as
 *     "no counterexample found", not as a proof.
 *
 * WHAT SHIPPING THE LIST COSTS AND REVEALS. `scrub-report.ts` is reached
 * statically from `src/index.tsx`, so this list is in the entry graph — the set
 * a maker must download before route `/` draws anything. Re-measured at this
 * head with the plugin that prints it, by emptying both arrays and rebuilding:
 * 573.66 kB → 576.12 kB raw, 169.55 kB → 170.53 kB gzip. So the check costs
 * 2.46 kB raw and 0.98 kB gzip on first paint. (The figures this replaces were
 * 572.25 → 575.04 and 169.01 → 170.17, quoting a 1.16 kB gzip delta. The delta
 * is the number that matters and it did not reproduce; the absolutes move with
 * every change to the entry graph, so they are only meaningful with the head
 * they were taken at, which is why this one says so.)
 *
 * AND WHAT IT REVEALS is worth saying out loud, because it is a cost of a
 * different kind: the production bundle of this app now contains a list of 179
 * identifiers naming most of its internal components and screens. That is
 * readable by anyone who loads the app. It is not customer data and this app has
 * no security that depends on the names of its components — the bundle already
 * contains its whole client-side behaviour — but it is a more complete map of
 * the app than the minified code alone was, and it is the kind of thing worth
 * knowing before deciding to grow this list.
 *
 * So in production this list mostly REDACTS, and the trail degrades to a depth
 * plus the handful of labels React hardcodes (`Suspense`, `Lazy`, `Memo`). That
 * is the honest value of the field, and it is also the argument for keeping the
 * check rather than the field: esbuild does NOT mangle property names, so the
 * one name that would still arrive verbatim in production is the one inferred
 * from a computed key — the leak. The list redacts precisely the string that
 * survives minification.
 */

/**
 * The labels React writes for its own internals rather than reading off a
 * function. They are string literals in React's bundle, they survive
 * minification, and none of them can be anything but themselves.
 */
const REACT_OWN_LABELS = [
'Suspense',
'SuspenseList',
'Fragment',
'Profiler',
'StrictMode',
'Lazy',
'Memo',
'ForwardRef',
'Portal',
'Cache',
'DehydratedFragment',
'Activity',
'ViewTransition'];


/** Scanned from this app's own `.tsx` source. See the header. */
const OURS = [
'AccountMenu',
'AccountTab',
'AdvertisingConsent',
'App',
'AppRoutes',
'AppShell',
'ArrowLeftIcon',
'ArrowRightIcon',
'ArtefactDesigner',
'ArtefactDesignerView',
'ArtefactOptions',
'ArtefactRail',
'ArtefactRenderer',
'AuthContext',
'AuthContextValue',
'AuthProvider',
'AuthSplash',
'Billing',
'BillingInterval',
'BillingResult',
'BillingReturn',
'BomEditor',
'BrowserRouter',
'Button',
'Callout',
'CandleSafetySymbols',
'Canvas',
'Card',
'CatalogueSkeleton',
'CategoryId',
'CeMark',
'ChangePasswordForm',
'Check',
'CheckIcon',
'Checkbox',
'ChevronRightIcon',
'ChevronUpIcon',
'CircleIcon',
'ColumnsIcon',
'ComponentDetail',
'ComponentTable',
'ConformityStore',
'ConsentPreferences',
'ConsentSection',
'CosmeticLabel',
'CrashScreen',
'CreditCardIcon',
'CurrentPlan',
'DataSection',
'DerivationPanel',
'DeviceCarton',
'DeviceLeaflet',
'Dialog',
'DiffRow',
'Divider',
'DocumentInbox',
'DocumentKind',
'DocumentSource',
'DownloadIcon',
'EmptyState',
'EntitlementContext',
'EntitlementProvider',
'EntitlementValue',
'ErrorBoundary',
'Expandable',
'ExternalLink',
'ExternalLinkIcon',
'Field',
'FormError',
'FormStatus',
'FragranceLabel',
'HTMLButtonElement',
'HTMLDivElement',
'HTMLInputElement',
'HTMLSelectElement',
'Icon',
'IdentitySection',
'IdentityTab',
'ImportFlow',
'IngredientDetail',
'IngredientTable',
'Input',
'IntervalToggle',
'Link',
'ListingBlock',
'LogOutIcon',
'Logo',
'Market',
'MaterialClass',
'MaterialDetail',
'Materials',
'MetaTrackingProvider',
'MinusIcon',
'MixtureEditor',
'NavLink',
'Navigate',
'NewProductDialog',
'NoAccountNotice',
'NotConfigured',
'PackageIcon',
'PackagingDetail',
'PackagingTable',
'PageHeader',
'PaoSymbol',
'ParsedField',
'PasswordField',
'PasswordSection',
'PencilIcon',
'PhasedEditor',
'Pictogram',
'Pill',
'PlanCard',
'PlanCatalogue',
'PlanLadder',
'PlanNotice',
'PlusIcon',
'PreferencesTab',
'ProductPipeline',
'Products',
'ProductsContext',
'ProductsProvider',
'ProductsValue',
'RatingPlate',
'Records',
'RefreshCwIcon',
'RequireAuth',
'RequiredKey',
'RequiredMark',
'Route',
'RoutedScreens',
'Routes',
'Row',
'Ruler',
'RulerIcon',
'SaveIcon',
'ScreenLoading',
'SdsDocument',
'SdsSummary',
'Section',
'SectionTitle',
'Select',
'Session',
'SetPasswordCard',
'Settings',
'SettingsIcon',
'SignInDidNotCarry',
'SignOutRow',
'Skeleton',
'SkuLimitNotice',
'Spec',
'Specification',
'SpecificationView',
'StageId',
'State',
'Studio',
'Surface',
'TeamTab',
'Toaster',
'TriangleAlertIcon',
'UploadIcon',
'UserIcon',
'WeeeBin',
'Why',
'WorkspaceContext',
'WorkspaceProvider',
'WorkspaceValue'];


/** The whole allow-list, as a Set because it is looked up per trail entry. */
export const APP_COMPONENT_NAMES: ReadonlySet<string> = new Set([...OURS, ...REACT_OWN_LABELS]);

/** Exported for the guard test, which checks each half against a different rule. */
export const SCANNED_FROM_OUR_SOURCE: readonly string[] = OURS;
export const REACT_BUILT_IN_LABELS: readonly string[] = REACT_OWN_LABELS;
