/**
 * Every component name this app is allowed to repeat out loud in a crash report.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY A LIST AND NOT A SHAPE — READ scrub-report.ts's "THE RULE" SECTION FIRST
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * React writes a component's name into the component stack from
 * `type.displayName || type.name`, and `type.name` is a string V8 INFERRED. It
 * infers it from whatever produced the function, and one of the things that
 * produces a function in an app like this is a data-derived key:
 *
 *     const screens = { [batch.code]: () => <Sheet /> };
 *     const Screen = screens[batch.code];   // Screen.name === 'BL240417A'
 *
 * That is the same mechanism that had `frames[].function` deleted from this
 * repo, one level up the tree, and it was MEASURED putting `BL240417A` on the
 * real Sentry wire through `extra.component_trail` before this list existed.
 * `[A-Za-z_$][A-Za-z0-9_$.]{0,63}` cannot tell that string from `Specification`
 * — nothing can, which is the whole reason the rule is a list.
 *
 * THE PROPERTY THAT MAKES THIS SAFE IS NOT THAT THE LIST IS COMPLETE. It is
 * that every string in it is an identifier that occurs in THIS REPOSITORY'S OWN
 * SOURCE, so it cannot be a value read from a customer's product — a batch
 * code, a supplier, an unlaunched product name — unless somebody typed that
 * value into our source, in which case it was ours to say. `app-component-
 * names.guard.test.ts` asserts exactly that property, name by name, against the
 * real source tree.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW IT WAS PRODUCED, AND WHY IT IS DELIBERATELY OVER-INCLUSIVE
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * A scan of this app's own non-test `.tsx` files for
 *
 *   - `function X` / `class X` / `const X =` where X is PascalCase,
 *   - `<X` — anything rendered as a JSX element, which is how third-party
 *     components that appear in OUR tree (`Toaster`, `Route`, `NavLink`) get in,
 *   - any `displayName: 'X'`,
 *
 * with SCREAMING_CASE constants dropped. The guard test runs the same scan.
 *
 * WHY IT IS CHECKED IN RATHER THAN GENERATED BY THE BUILD. A Vite plugin
 * resolving a virtual module would remove the staleness entirely, and it was the
 * first thing tried. It does not survive contact with this repo: `vitest.config.ts`
 * is a SEPARATE config from `vite.config.ts` and carries only `react()`, so a
 * plugin added to the build would not exist under test — and the test is where
 * the safety property is asserted. The choice would be to duplicate the plugin
 * into both configs (two places to forget) or to let the suite run against a
 * list the build does not use (a test of something that does not ship). A file
 * plus a guard test is the same idea with neither problem.
 *
 * It therefore contains things that are not components at all — `Session`,
 * `HTMLDivElement`, `ParsedField` — because the regex cannot tell a generic
 * parameter from a JSX tag. THAT DIRECTION IS FREE. The risk this list carries
 * is a name in it that is NOT in our source; a name in it that is in our source
 * and is not a component is a string we shipped, which is exactly what the list
 * is for. Trimming it by hand would be work with no safety in it.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * IT WILL GO STALE, AND THAT IS THE SAME BARGAIN AS SCREEN_NAMES AND ROUTES
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Add a component and forget this file and its name is reported as `[redacted]`:
 * a trail loses a label, a customer loses nothing. The guard test deliberately
 * does NOT assert equality with the scan, because a test that reddens on every
 * new component would be a test people delete. It asserts the direction that
 * matters — nothing here that is not ours — and leaves the other one to rot
 * safely.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THE TRAIL IS WORTH IN THE BUILD THAT ACTUALLY REPORTS — MEASURED
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Do not read a rich trail into a production issue. esbuild mangles top-level
 * bindings, so our own component names are GONE from a production bundle:
 * `npm run build` on this branch emits no `CandleSafetySymbols`, no `PlanLadder`,
 * no `CrashScreen`, no `DerivationPanel` anywhere in `dist/assets/*.js`. What
 * React puts in a production component stack for those is a two-letter binding,
 * which is not on this list and is reported as `[redacted]`.
 *
 * AND IT IS NOT FREE. `scrub-report.ts` is reached statically from
 * `src/index.tsx`, so this list is in the entry graph — the set a maker must
 * download before route `/` draws anything. Measured on this branch with the
 * plugin that prints it: 572.25 kB → 575.04 kB raw, 169.01 kB → 170.17 kB gzip.
 * 1.16 kB gzip is what the check costs on first paint, which is worth it for a
 * field that was putting batch codes in a third party's database and would not
 * be worth it for much else.
 *
 * So in production this list mostly REDACTS, and the trail degrades to a depth
 * plus the handful of labels React hardcodes (`Suspense`, `Lazy`, `Memo`). That
 * is the honest value of the field, and it is also the argument for keeping the
 * check rather than the field: esbuild does NOT mangle property names, so the
 * one name that would still arrive verbatim in production is the one inferred
 * from a computed key — the leak. The list redacts precisely the string that
 * survives minification.
 */

/**
 * The labels React writes for its own internals rather than reading off a
 * function. They are string literals in React's bundle, they survive
 * minification, and none of them can be anything but themselves.
 */
const REACT_OWN_LABELS = [
'Suspense',
'SuspenseList',
'Fragment',
'Profiler',
'StrictMode',
'Lazy',
'Memo',
'ForwardRef',
'Portal',
'Cache',
'DehydratedFragment',
'Activity',
'ViewTransition'];


/** Scanned from this app's own `.tsx` source. See the header. */
const OURS = [
'AccountMenu',
'AccountTab',
'AdvertisingConsent',
'App',
'AppRoutes',
'AppShell',
'ArrowLeftIcon',
'ArrowRightIcon',
'ArtefactDesigner',
'ArtefactDesignerView',
'ArtefactOptions',
'ArtefactRail',
'ArtefactRenderer',
'AuthContext',
'AuthContextValue',
'AuthProvider',
'AuthSplash',
'Billing',
'BillingInterval',
'BillingResult',
'BillingReturn',
'BomEditor',
'BrowserRouter',
'Button',
'Callout',
'CandleSafetySymbols',
'Canvas',
'Card',
'CatalogueSkeleton',
'CategoryId',
'CeMark',
'ChangePasswordForm',
'Check',
'CheckIcon',
'Checkbox',
'ChevronRightIcon',
'ChevronUpIcon',
'CircleIcon',
'ColumnsIcon',
'ComponentDetail',
'ComponentTable',
'ConformityStore',
'ConsentPreferences',
'ConsentSection',
'CosmeticLabel',
'CrashScreen',
'CreditCardIcon',
'CurrentPlan',
'DataSection',
'DerivationPanel',
'DeviceCarton',
'DeviceLeaflet',
'Dialog',
'DiffRow',
'Divider',
'DocumentInbox',
'DocumentKind',
'DocumentSource',
'DownloadIcon',
'EmptyState',
'EntitlementContext',
'EntitlementProvider',
'EntitlementValue',
'ErrorBoundary',
'Expandable',
'ExternalLink',
'ExternalLinkIcon',
'Field',
'FormError',
'FormStatus',
'FragranceLabel',
'HTMLButtonElement',
'HTMLDivElement',
'HTMLInputElement',
'HTMLSelectElement',
'Icon',
'IdentitySection',
'IdentityTab',
'ImportFlow',
'IngredientDetail',
'IngredientTable',
'Input',
'IntervalToggle',
'Link',
'ListingBlock',
'LogOutIcon',
'Logo',
'Market',
'MaterialClass',
'MaterialDetail',
'Materials',
'MetaTrackingProvider',
'MinusIcon',
'MixtureEditor',
'NavLink',
'Navigate',
'NewProductDialog',
'NoAccountNotice',
'NotConfigured',
'PackageIcon',
'PackagingDetail',
'PackagingTable',
'PageHeader',
'PaoSymbol',
'ParsedField',
'PasswordField',
'PasswordSection',
'PencilIcon',
'PhasedEditor',
'Pictogram',
'Pill',
'PlanCard',
'PlanCatalogue',
'PlanLadder',
'PlanNotice',
'PlusIcon',
'PreferencesTab',
'ProductPipeline',
'Products',
'ProductsContext',
'ProductsProvider',
'ProductsValue',
'RatingPlate',
'Records',
'RefreshCwIcon',
'RequireAuth',
'RequiredKey',
'RequiredMark',
'Route',
'RoutedScreens',
'Routes',
'Row',
'Ruler',
'RulerIcon',
'SaveIcon',
'ScreenLoading',
'SdsDocument',
'SdsSummary',
'Section',
'SectionTitle',
'Select',
'Session',
'SetPasswordCard',
'Settings',
'SettingsIcon',
'SignInDidNotCarry',
'SignOutRow',
'Skeleton',
'SkuLimitNotice',
'Spec',
'Specification',
'SpecificationView',
'StageId',
'State',
'Studio',
'Surface',
'TeamTab',
'Toaster',
'TriangleAlertIcon',
'UploadIcon',
'UserIcon',
'WeeeBin',
'Why',
'WorkspaceContext',
'WorkspaceProvider',
'WorkspaceValue'];


/** The whole allow-list, as a Set because it is looked up per trail entry. */
export const APP_COMPONENT_NAMES: ReadonlySet<string> = new Set([...OURS, ...REACT_OWN_LABELS]);

/** Exported for the guard test, which checks each half against a different rule. */
export const SCANNED_FROM_OUR_SOURCE: readonly string[] = OURS;
export const REACT_BUILT_IN_LABELS: readonly string[] = REACT_OWN_LABELS;
